import { GENERATORS } from '../src/js/core/primitives.js';
import * as P from '../src/js/core/polymesh.js';
const manifold = (pm) => { const t = pm.topo; let open=0, bad=0; t.edgeFaces.forEach(f=>{ if(f.length===1) open++; if(f.length>2) bad++; }); 
  // orientation consistency: every directed edge unique
  let dup=0; const s=new Set(); pm.f.forEach(f=>f.forEach((a,i)=>{const k=P.dkey(a,f[(i+1)%f.length]); if(s.has(k)) dup++; s.add(k);})); return {open,bad,dup}; };
const report=(name,pm)=>{ const m=manifold(pm); const st=pm.stats(); console.log(name.padEnd(22), 'V',st.verts,'F',st.faces,'vol',P.signedVolume(pm).toFixed(3),'open',m.open,'nonman',m.bad,'dupDir',m.dup, pm.uv? 'uv ok':'no uv'); P.buildGeometry(pm); };
for (const [k,g] of Object.entries(GENERATORS)) report(k, g({}));
const cube = GENERATORS.polyCube({});
report('extrude top', P.opExtrudeFaces(cube,{faces:[1],thickness:0.5}).mesh);
report('extrude 2 sep', P.opExtrudeFaces(cube,{faces:[0,1],thickness:0.5,keepFacesTogether:false}).mesh);
report('inset', P.opExtrudeFaces(cube,{faces:[1],thickness:0,offset:0.3}).mesh);
const e = cube.topo.edges;
report('bevel 1 edge', P.opBevel(cube,{edges:[e[0]]}).mesh);
report('bevel all', P.opBevel(cube,{edges:e}).mesh);
report('bevel 2', P.opBevel(cube,{edges:[e[0],e[1]]}).mesh);
const pl = GENERATORS.polyPlane({});
report('bevel plane edge', P.opBevel(pl,{edges:[pl.topo.edges[60]]}).mesh);
report('edge loop cube', P.opInsertEdgeLoop(cube,{edge:e[0],t:0.3}).mesh);
const cyl=GENERATORS.polyCylinder({});
const vert = cyl.topo.edges.find(([a,b])=>Math.abs(cyl.v[a][1]-cyl.v[b][1])>1);
report('edge loop cyl', P.opInsertEdgeLoop(cyl,{edge:vert,t:0.5}).mesh);
report('edge loop x3', P.opInsertEdgeLoop(cyl,{edge:vert,multiple:3}).mesh);
report('smooth cube', P.opSmooth(cube,{divisions:2}).mesh);
report('adddiv', P.opAddDivisions(cube,{divisions:1}).mesh);
report('adddiv faces', P.opAddDivisions(cube,{faces:[0]}).mesh);
report('triangulate', P.opTriangulate(cyl,{}).mesh);
report('poke', P.opPoke(cube,{faces:[0,1]}).mesh);
report('delete face', P.opDeleteFaces(cube,{faces:[0]}).mesh);
report('fill hole', P.opFillHole(P.opDeleteFaces(cube,{faces:[0]}).mesh,{}).mesh);
const se=GENERATORS.polySphere({});
report('mirror half', P.opMirror(P.opDeleteFaces(se,{faces:se.f.map((f,i)=>i).filter(i=>se.faceCenter(i)[0]<0)}).mesh,{axis:0}).mesh);
report('delete edge', P.opDeleteEdges(GENERATORS.polyPlane({subdivisionsWidth:2,subdivisionsHeight:2}),{edges:[[1,4]]}).mesh);
report('merge center', P.opMergeToCenter(cube,{groups:[[0,1]]}).mesh);
report('merge verts', P.opMergeVertices(P.combineMeshes([{mesh:cube},{mesh:cube}]),{}).mesh);
report('chamfer v', P.opChamferVertex(cube,{verts:[0]}).mesh);
const two = P.combineMeshes([{mesh:cube},{mesh:P.transformMesh(cube,new (await import('three')).Matrix4().makeTranslation(0,3,0))}]);
// bridge top face of first with bottom face of second
const topF = two.f.findIndex((f,i)=>{const c=two.faceCenter(i);return Math.abs(c[1]-0.5)<1e-6;});
const botF = two.f.findIndex((f,i)=>{const c=two.faceCenter(i);return Math.abs(c[1]-2.5)<1e-6;});
report('bridge faces', P.opBridge(two,{faces:[topF,botF],divisions:2}).mesh);
const sp = P.opSplit(cube,{points:[{edge:e[0],t:0.5},{edge:e[2],t:0.5}]}); report('split', sp.mesh);
report('quadrangulate', P.opQuadrangulate(P.opTriangulate(cube,{}).mesh,{}).mesh);
report('extrude edges', P.opExtrudeEdges(pl,{edges:[pl.topo.edges.find(([a,b])=>pl.topo.edgeFaces[pl.edgeIndex(a,b)].length===1)],thickness:1}).mesh);
for (const m of ['planar','cylindrical','spherical','automatic']) P.opProjectUV(cube,{mode:m});
console.log('ok');
